# permissions for end users to view gravs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grav-viewer-role
rules:
- apiGroups:
  - operator.adysof.com
  resources:
  - gravs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.adysof.com
  resources:
  - gravs/status
  verbs:
  - get
